#!/bin/bash

# Print all commands executed if DEBUG mode enabled
[ -n "${DEBUG:-""}" ] && set -x

dir="${SECURITY_OUTPUT_DIR:-/var/tmp/chainlink}"
mkdir -p $dir

# create or verify existence of credentials files based on set "WALLET/API" environment variables
chainlink-helper security setup-credentials
